export enum ParamType {
    ActionPoint = "ACTION_POINT",
    AllPlayers = "ALL_PLAYERS",
    AllianceType = "ALLIANCE_TYPE",
    AnyCreature = "ANY_CREATURE",
    AudioType = "AUDIO_TYPE",
    Auto = "AUTO",
    AvailVars = "AVAIL_VARS",
    Binary = "BINARY",
    Button = "BUTTON",
    Byte = "BYTE",
    CampaignFlag = "CAMPAIGN_FLAG",
    ClassicBug = "CLASSIC_BUG",
    CompCheck = "COMP_CHECK",
    CompEvent = "COMP_EVENT",
    CompProcess = "COMP_PROCESS",
    CompareOperator = "COMPARE_OPERATOR",
    Computer = "COMPUTER",
    Creature = "CREATURE",
    CreatureConfig = "CREATURE_CONFIG",
    CreatureGlobal = "CREATURE_GLOBAL",
    CreatureProperty = "CREATURE_PROPERTY",
    CreatureSpell = "CREATURE_SPELL",
    CreatureTendency = "CREATURE_TENDENCY",
    Criterion = "CRITERION",
    CustomBox = "CUSTOM_BOX",
    DisplayVarTargetType = "DISPLAY_VAR_TARGET_TYPE",
    Door = "DOOR",
    DoorProperty = "DOOR_PROPERTY",
    DoorConfig = "DOOR_CONFIG",
    Effect = "EFFECT",
    EffectGenerator = "EFFECT_GENERATOR",
    EffectGeneratorProperty = "EFFECT_GENERATOR_PROPERTY",
    FillType = "FILL_TYPE",
    Flag = "FLAG",
    GameRule = "GAME_RULE",
    Global = "GLOBAL",
    Gold = "GOLD",
    HeadFor = "HEAD_FOR",
    HeroGate = "HERO_GATE",
    Job = "JOB",
    Keeper = "KEEPER",
    KeeperIndex = "KEEPER_INDEX",
    Location = "LOCATION",
    LockState = "LOCK_STATE",
    Lvl = "LVL",
    IncreaseConfig = "INCREASE_CONFIG",
    MsgNumber = "MSG_NUMBER",
    NewParty = "NEW_PARTY",
    NonNegNumber = "NUMBER+",
    Number = "NUMBER",
    NumberCompound = "NUMBER_COMPOUND",
    NumberMinNegative400 = "NUMBER_MIN_NEGATIVE_400",
    Object = "OBJECT",
    ObjectConfig = "OBJECT_CONFIG",
    Objective = "OBJECTIVE",
    ObjectGenre = "OBJECT_GENRE",
    ObjectProperty = "OBJECT_PROPERTY",
    OneToTen = "1-10",
    Operation = "OPERATION",
    Party = "PARTY",
    PaidOrFree = "PAID_OR_FREE",
    Player = "PLAYER",
    PlayerColor = "PLAYER_COLOR",
    PlayerGood = "PLAYER_GOOD",
    PlayerModifier = "PLAYER_MODIFIER",
    Power = "POWER",
    PowerConfig = "POWER_CONFIG",
    PowerConfigCastability = "POWER_CONFIG_CASTABILITY",
    PowerLvl = "POWER_LVL",
    Range = "RANGE",
    ReadVar = "READABLE_VAR",
    ReadSetVar = "READSET_VAR",
    ResearchType = "RESEARCH_TYPE",
    Room = "ROOM",
    RoomAll = "ROOM_ALL",
    RoomAvailability = "ROOM_AVAILABILITY",
    RoomConfig = "ROOM_CONFIG",
    RoomConfigUsedCapacity = "ROOM_CONFIG_USED_CAPACITY",
    RoomConfigTotalCapacity = "ROOM_CONFIG_TOTAL_CAPACITY",
    RoomProperty = "ROOM_PROPERTY",
    RoomRole = "ROOM_ROLE",
    Rule = "RULE",
    RuleAction = "RULE_ACTION",
    RuleSlot = "RULE_SLOT",
    SacrificeCmd = "SACRIFICE_CMD",
    SetVar = "SETTABLE_VAR",
    Slab = "SLAB",
    SlabType = "SLAB_TYPE",
    Spell = "SPELL",
    Subtile = "SUBTILE",
    Text = "TEXT",
    Texture = "TEXTURE",
    Time = "TIME",
    Timer = "TIMER",
    Trap = "TRAP",
    TrapActivated = "TRAP_ACIVATED",
    TrapActivationType = "TRAP_ACTIVATION_TYPE",
    TrapConfig = "TRAP_CONFIG",
    TrapTriggerType = "TRAP_TRIGGER_TYPE",
    Unknown = "UNKNOWN",
    UpdateFunction = "UPDATE_FUNCTION",
    ViewType = "VIEW_TYPE",
    Void = "VOID",
    Version = "VERSION",
    Zero = "ZERO"
}

export const FINAL_PARAM_TYPES: Readonly<ParamType[]> = [
    ParamType.AudioType, ParamType.Button, ParamType.CompareOperator,
    ParamType.CreatureConfig, ParamType.CreatureGlobal, ParamType.CreatureProperty,
    ParamType.CreatureTendency, ParamType.DisplayVarTargetType,
    ParamType.DoorConfig, ParamType.FillType, ParamType.GameRule, ParamType.Global,
    ParamType.HeadFor, ParamType.MsgNumber, ParamType.NewParty, ParamType.Operation,
    ParamType.ObjectConfig, ParamType.Range, ParamType.ResearchType,
    ParamType.Rule, ParamType.RuleAction, ParamType.RuleSlot,
    ParamType.SacrificeCmd, ParamType.Text, ParamType.TrapActivationType, ParamType.TrapConfig,
    ParamType.TrapTriggerType, ParamType.Version, ParamType.Void,
];

export const CONSECUTIVE_TYPES: Readonly<ParamType[]> = [
    ParamType.Number,
    ParamType.Byte,
    ParamType.Slab,
    ParamType.Subtile,
    ParamType.Time,
    ParamType.PowerLvl,
    ParamType.OneToTen,
    ParamType.NonNegNumber,
    ParamType.Gold,
];